### ISSUE TITLE
Please translate README.md to english

### ISSUE THREAD

**Issue by playday3008** [TXIuTnVsbA/Osiris_Edit#2]
or create README_eng.md

**Comment by Fuwn** [comment]
@playday3008 added this in a [pr](https://github.com/TXIuTnVsbA/Osiris_Edit/pull/4) i just made, hopefully gets accepted.

**Comment by TXIuTnVsbA** [comment]
> @playday3008 added this in a [pr](https://github.com/TXIuTnVsbA/Osiris_Edit/pull/4) i just made, hopefully gets accepted.

If you know the author of "lua addon", please tell the author of "lua addon" to contact me as soon as possible, I want to work with him to research things about lua.

**Comment by TXIuTnVsbA** [comment]
> or create README_eng.md

If you know the author of "lua addon", please tell the author of "lua addon" to contact me as soon as possible, I want to work with him to research things about lua.
